'10100':
  children: *10100
  '10200':
    children: *10200
    name: Popori_F_Warrior_Lv02_Combo_Attack 01
    totalAtk: "+37%"
  '10300':
    children: *10300
    name: Popori_F_Warrior_Lv03_Combo_Attack 01
    totalAtk: "+100%"
  '10400':
    children: *10400
    name: Popori_F_Warrior_Lv04_Combo_Attack 01
    totalAtk: "+192%"
  '10500':
    children: *10500
    name: Popori_F_Warrior_Lv05_Combo_Attack 01
    totalAtk: "+326%"
  '10600':
    children: *10600
    name: Popori_F_Warrior_Lv06_Combo_Attack 01
    totalAtk: "+521%"
  '10700':
    children: *10700
    name: Popori_F_Warrior_Lv07_Combo_Attack 01
    totalAtk: "+806%"
  '10800':
    children: *10800
    name: Popori_F_Warrior_Lv08_Combo_Attack 01
    totalAtk: "+1222%"
  '10900':
    children: *10900
    name: Popori_F_Warrior_Lv09_Combo_Attack 01
    totalAtk: "+1829%"
  '11000':
    children: *11000
    name: Popori_F_Warrior_Lv10_Combo_Attack 01
    totalAtk: "+2715%"
  '11100':
    children: *11100
    name: Popori_F_Warrior_Lv11_Combo_Attack 01
    totalAtk: "+4008%"
  '11200':
    children: *11200
    name: Popori_F_Warrior_Lv12_Combo_Attack 01
    totalAtk: "+5528%"
'30100':
  '30200':
    name: Popori_F_Warrior_Lv02_Dual Sword Dancing_Attack 01
    totalAtk: "+37%"
  '30300':
    name: Popori_F_Warrior_Lv03_Dual Sword Dancing_Attack 01
    totalAtk: "+76%"
'40100':
  '40200':
    name: Popori_F_Warrior_Lv02_Concentrate Attack_Attack_Single 01
    totalAtk: "+46%"
  '40300':
    name: Popori_F_Warrior_Lv03_Concentrate Attack_Attack_Single 01
    totalAtk: "+113%"
  '40400':
    name: Popori_F_Warrior_Lv04_Concentrate Attack_Attack_Single 01
    totalAtk: "+211%"
  '40500':
    name: Popori_F_Warrior_Lv05_Concentrate Attack_Attack_Single 01
    totalAtk: "+353%"
  '40600':
    name: Popori_F_Warrior_Lv06_Concentrate Attack_Attack_Single 01
    totalAtk: "+561%"
  '40700':
    name: Popori_F_Warrior_Lv07_Concentrate Attack_Attack_Single 01
    totalAtk: "+865%"
  '40800':
    name: Popori_F_Warrior_Lv08_Concentrate Attack_Attack_Single 01
    totalAtk: "+1308%"
  '40900':
    name: Popori_F_Warrior_Lv09_Concentrate Attack_Attack_Single 01
    totalAtk: "+1829%"
'100100':
  '100200':
    name: Popori_F_Warrior_Lv02_Evasion Attack_Attack 01
    totalAtk: "+46%"
  '100300':
    name: Popori_F_Warrior_Lv03_Evasion Attack_Attack 01
    totalAtk: "+113%"
  '100400':
    name: Popori_F_Warrior_Lv04_Evasion Attack_Attack 01
    totalAtk: "+211%"
  '100500':
    name: Popori_F_Warrior_Lv05_Evasion Attack_Attack 01
    totalAtk: "+353%"
  '100600':
    name: Popori_F_Warrior_Lv06_Evasion Attack_Attack 01
    totalAtk: "+561%"
  '100700':
    name: Popori_F_Warrior_Lv07_Evasion Attack_Attack 01
    totalAtk: "+928%"
'110100':
  '110200':
    name: Popori_F_Warrior_Lv02_Poison Blow_Attack 01
    totalAtk: "+46%"
  '110300':
    name: Popori_F_Warrior_Lv03_Poison Blow_Attack 01
    totalAtk: "+113%"
  '110400':
    name: Popori_F_Warrior_Lv04_Poison Blow_Attack 01
    totalAtk: "+211%"
  '110500':
    name: Popori_F_Warrior_Lv05_Poison Blow_Attack 01
    totalAtk: "+353%"
  '110600':
    name: Popori_F_Warrior_Lv06_Poison Blow_Attack 01
    totalAtk: "+561%"
  '110700':
    name: Popori_F_Warrior_Lv07_Poison Blow_Attack 01
    totalAtk: "+865%"
  '110800':
    name: Popori_F_Warrior_Lv08_Poison Blow_Attack 01
    totalAtk: "+1308%"
  '110900':
    name: Popori_F_Warrior_Lv09_Poison Blow_Attack 01
    totalAtk: "+1955%"
  '111000':
    name: Popori_F_Warrior_Lv10_Poison Blow_Attack 01
    totalAtk: "+2898%"
  '111100':
    name: Popori_F_Warrior_Lv11_Poison Blow_Attack 01
    totalAtk: "+4008%"
'120100':
  '120200':
    name: Popori_F_Warrior_Lv02_Down Blow_Attack 01
    totalAtk: "+46%"
  '120300':
    name: Popori_F_Warrior_Lv03_Down Blow_Attack 01
    totalAtk: "+113%"
  '120400':
    name: Popori_F_Warrior_Lv04_Down Blow_Attack 01
    totalAtk: "+211%"
  '120500':
    name: Popori_F_Warrior_Lv05_Down Blow_Attack 01
    totalAtk: "+353%"
  '120600':
    name: Popori_F_Warrior_Lv06_Down Blow_Attack 01
    totalAtk: "+561%"
  '120700':
    name: Popori_F_Warrior_Lv07_Down Blow_Attack 01
    totalAtk: "+865%"
  '120800':
    name: Popori_F_Warrior_Lv08_Down Blow_Attack 01
    totalAtk: "+1222%"
'130100':
  '130200':
    name: Popori_F_Warrior_Lv02_Rising Attack_Attack 01
    totalAtk: "+46%"
  '130300':
    name: Popori_F_Warrior_Lv03_Rising Attack_Attack 01
    totalAtk: "+113%"
  '130400':
    name: Popori_F_Warrior_Lv04_Rising Attack_Attack 01
    totalAtk: "+211%"
  '130500':
    name: Popori_F_Warrior_Lv05_Rising Attack_Attack 01
    totalAtk: "+353%"
  '130600':
    name: Popori_F_Warrior_Lv06_Rising Attack_Attack 01
    totalAtk: "+561%"
  '130700':
    name: Popori_F_Warrior_Lv07_Rising Attack_Attack 01
    totalAtk: "+865%"
  '130800':
    name: Popori_F_Warrior_Lv08_Rising Attack_Attack 01
    totalAtk: "+1308%"
  '130900':
    name: Popori_F_Warrior_Lv09_Rising Attack_Attack 01
    totalAtk: "+1955%"
  '131000':
    name: Popori_F_Warrior_Lv10_Rising Attack_Attack 01
    totalAtk: "+2715%"
'170100':
  '170200':
    name: Popori_F_Warrior_Lv02_All Round Slash_Attack 01
    totalAtk: "+46%"
  '170300':
    name: Popori_F_Warrior_Lv03_All Round Slash_Attack 01
    totalAtk: "+113%"
  '170400':
    name: Popori_F_Warrior_Lv04_All Round Slash_Attack 01
    totalAtk: "+211%"
  '170500':
    children: *170500
    name: Popori_F_Warrior_Lv05_All Round Slash_Attack 01
    totalAtk: "+353%"
  '170600':
    children: *170600
    name: Popori_F_Warrior_Lv06_All Round Slash_Attack 01
    totalAtk: "+561%"
  '170700':
    children: *170700
    name: Popori_F_Warrior_Lv07_All Round Slash_Attack 01
    totalAtk: "+806%"
'180100':
  '180200':
    name: Popori_F_Warrior_Lv02_Aggravating Strike_Attack 01
    totalAtk: "+46%"
  '180300':
    name: Popori_F_Warrior_Lv03_Aggravating Strike_Attack 01
    totalAtk: "+113%"
  '180400':
    name: Popori_F_Warrior_Lv04_Aggravating Strike_Attack 01
    totalAtk: "+211%"
  '180500':
    name: Popori_F_Warrior_Lv05_Aggravating Strike_Attack 01
    totalAtk: "+353%"
  '180600':
    name: Popori_F_Warrior_Lv06_Aggravating Strike_Attack 01
    totalAtk: "+561%"
  '180700':
    name: Popori_F_Warrior_Lv07_Aggravating Strike_Attack 01
    totalAtk: "+865%"
  '180800':
    name: Popori_F_Warrior_Lv08_Aggravating Strike_Attack 01
    totalAtk: "+1308%"
  '180900':
    name: Popori_F_Warrior_Lv09_Aggravating Strike_Attack 01
    totalAtk: "+1955%"
  '181000':
    name: Popori_F_Warrior_Lv10_Aggravating Strike_Attack 01
    totalAtk: "+2898%"
  '181100':
    children: *181100
    name: Popori_F_Warrior_Lv11_Aggravating Strike_Attack_Start 01
    totalAtk: "+4559%"
'190100':
  children: *190100
  '190200':
    children: *190200
    name: Popori_F_Warrior_Lv02_Tenacious Attack_Attack 01
    totalAtk: "+46%"
  '190300':
    children: *190300
    name: Popori_F_Warrior_Lv03_Tenacious Attack_Attack 01
    totalAtk: "+113%"
  '190400':
    children: *190400
    name: Popori_F_Warrior_Lv04_Tenacious Attack_Attack 01
    totalAtk: "+211%"
  '190500':
    children: *190500
    name: Popori_F_Warrior_Lv05_Tenacious Attack_Attack 01
    totalAtk: "+353%"
  '190600':
    children: *190600
    name: Popori_F_Warrior_Lv06_Tenacious Attack_Attack 01
    totalAtk: "+561%"
  '190700':
    children: *190700
    name: Popori_F_Warrior_Lv07_Tenacious Attack_Attack 01
    totalAtk: "+865%"
  '190800':
    children: *190800
    name: Popori_F_Warrior_Lv08_Tenacious Attack_Attack 01
    totalAtk: "+1308%"
  '190900':
    children: *190900
    name: Popori_F_Warrior_Lv09_Tenacious Attack_Attack 01
    totalAtk: "+1955%"
  '191000':
    children: *191000
    name: Popori_F_Warrior_Lv10_Tenacious Attack_Attack 01
    totalAtk: "+2898%"
  '191100':
    children: *191100
    name: Popori_F_Warrior_Lv11_Tenacious Attack_Attack 01
    totalAtk: "+4008%"
'210100':
  '210200':
    name: Popori_F_Warrior_Lv02_Hard Slash_Attack 01
    totalAtk: "+46%"
  '210300':
    name: Popori_F_Warrior_Lv03_Hard Slash_Attack 01
    totalAtk: "+113%"
  '210400':
    name: Popori_F_Warrior_Lv04_Hard Slash_Attack 01
    totalAtk: "+211%"
  '210500':
    name: Popori_F_Warrior_Lv04_Hard Slash_Attack 01
    totalAtk: "+326%"
'220100':
  '220200':
    name: Popori_F_Warrior_Lv02_Catch Back Attack_Start 01
    totalAtk: "+231%"
'230100':
  '230200':
    name: Popori_F_Warrior_Lv02_Reversal Turning Attack_Start 01
    totalAtk: "+46%"
  '230300':
    name: Popori_F_Warrior_Lv02_Reversal Turning Attack_Start 01
    totalAtk: "+113%"
  '230400':
    name: Popori_F_Warrior_Lv02_Reversal Turning Attack_Start 01
    totalAtk: "+211%"
  '230500':
    name: Popori_F_Warrior_Lv02_Reversal Turning Attack_Start 01
    totalAtk: "+353%"
  '230600':
    name: Popori_F_Warrior_Lv02_Reversal Turning Attack_Start 01
    totalAtk: "+448%"
'270100':
  '270200':
    name: Popori_F_Warrior_Lv02_Heavy Bite_Attack 01
    totalAtk: "+57%"
  '270300':
    name: Popori_F_Warrior_Lv03_Heavy Bite_Attack 01
    totalAtk: "+135%"
  '270400':
    name: Popori_F_Warrior_Lv04_Heavy Bite_Attack 01
    totalAtk: "+252%"
  '270500':
    name: Popori_F_Warrior_Lv05_Heavy Bite_Attack 01
    totalAtk: "+429%"
  '270600':
    name: Popori_F_Warrior_Lv06_Heavy Bite_Attack 01
    totalAtk: "+508%"
  '270700':
    name: Popori_F_Warrior_Lv07_Heavy Bite_Attack 01
    totalAtk: "+787%"
  '270800':
    name: Popori_F_Warrior_Lv08_Heavy Bite_Attack 01
    totalAtk: "+1278%"
  '270900':
    name: Popori_F_Warrior_Lv09_Heavy Bite_Attack 01
    totalAtk: "+1115%"
  '271000':
    name: Popori_F_Warrior_Lv10_Heavy Bite_Attack 01
    totalAtk: "+787%"
  '271100':
    name: Popori_F_Warrior_Lv11_Heavy Bite_Attack 01
    totalAtk: "+787%"
'280100':
  '280200':
    name: Popori_F_Warrior_Lv02_No Rival Dancing_Rapid Piercing_Single Use Start 01
    totalAtk: "+46%"
  '280300':
    name: Popori_F_Warrior_Lv03_No Rival Dancing_Rapid Piercing_Single Use Start 01
    totalAtk: "+113%"
  '280400':
    name: Popori_F_Warrior_Lv04_No Rival Dancing_Rapid Piercing_Single Use Start 01
    totalAtk: "+211%"
  '280500':
    name: Popori_F_Warrior_Lv05_No Rival Dancing_Rapid Piercing_Single Use Start 01
    totalAtk: "+353%"
  '280600':
    name: Popori_F_Warrior_Lv06_No Rival Dancing_Rapid Piercing_Single Use Start 01
    totalAtk: "+561%"
  '280700':
    name: Popori_F_Warrior_Lv07_No Rival Dancing_Rapid Piercing_Single Use Start 01
    totalAtk: "+865%"
  '280800':
    name: Popori_F_Warrior_Lv08_No Rival Dancing_Rapid Piercing_Single Use Start 01
    totalAtk: "+1308%"
  '280900':
    name: Popori_F_Warrior_Lv09_No Rival Dancing_Rapid Piercing_Single Use Start 01
    totalAtk: "+1955%"
  '281000':
    name: Popori_F_Warrior_Lv10_No Rival Dancing_Rapid Piercing_Single Use Start 01
    totalAtk: "+3522%"
'290100':
  '290200':
    name: Popori_F_Warrior_Lv02_No Rival Dancing_Dual Slash_Single Use Start 01
    totalAtk: "+46%"
  '290300':
    name: Popori_F_Warrior_Lv03_No Rival Dancing_Dual Slash_Single Use Start 01
    totalAtk: "+113%"
  '290400':
    name: Popori_F_Warrior_Lv04_No Rival Dancing_Dual Slash_Single Use Start 01
    totalAtk: "+211%"
  '290500':
    name: Popori_F_Warrior_Lv05_No Rival Dancing_Dual Slash_Single Use Start 01
    totalAtk: "+353%"
  '290600':
    name: Popori_F_Warrior_Lv06_No Rival Dancing_Dual Slash_Single Use Start 01
    totalAtk: "+561%"
  '290700':
    name: Popori_F_Warrior_Lv07_No Rival Dancing_Dual Slash_Single Use Start 01
    totalAtk: "+865%"
  '290800':
    name: Popori_F_Warrior_Lv08_No Rival Dancing_Dual Slash_Single Use Start 01
    totalAtk: "+1308%"
  '290900':
    name: Popori_F_Warrior_Lv09_No Rival Dancing_Dual Slash_Single Use Start 01
    totalAtk: "+2382%"
'300100':
  '300200':
    name: Popori_F_Warrior_Lv02_Raker_Single Use Start 01
    totalAtk: "+46%"
  '300300':
    name: Popori_F_Warrior_Lv03_Raker_Single Use Start 01
    totalAtk: "+113%"
  '300400':
    name: Popori_F_Warrior_Lv04_Raker_Single Use Start 01
    totalAtk: "+211%"
  '300500':
    name: Popori_F_Warrior_Lv05_Raker_Single Use Start 01
    totalAtk: "+353%"
  '300600':
    name: Popori_F_Warrior_Lv05_Raker_Single Use Start 01
    totalAtk: "+561%"
  '300700':
    name: Popori_F_Warrior_Lv05_Raker_Single Use Start 01
    totalAtk: "+865%"
  '300800':
    name: Popori_F_Warrior_Lv05_Raker_Single Use Start 01
    totalAtk: "+1308%"
  '300900':
    name: Popori_F_Warrior_Lv05_Raker_Single Use Start 01
    totalAtk: "+1829%"
'310100':
  '310200':
    name: Popori_F_Warrior_Lv02_Rupture_Single Use Start 01
    totalAtk: "+46%"
  '310300':
    name: Popori_F_Warrior_Lv03_Rupture_Single Use Start 01
    totalAtk: "+113%"
  '310400':
    name: Popori_F_Warrior_Lv04_Rupture_Single Use Start 01
    totalAtk: "+211%"
  '310500':
    name: Popori_F_Warrior_Lv05_Rupture_Single Use Start 01
    totalAtk: "+353%"
  '310600':
    name: Popori_F_Warrior_Lv06_Rupture_Single Use Start 01
    totalAtk: "+561%"
  '310700':
    name: Popori_F_Warrior_Lv07_Rupture_Single Use Start 01
    totalAtk: "+865%"
  '310800':
    name: Popori_F_Warrior_Lv08_Rupture_Single Use Start 01
    totalAtk: "+1400%"
'330100':
  '330200':
    name: Popori_F_Warrior_Lv02_Shadow change Start 01
    totalAtk: "+37%"
