arun:
  arcadia:
    oblivion_woods:
      server:
        - "NpcData_3.xml"
        - "TerritoryData_3.xml"
      client:
        - "NpcData-00001.xml"
        - "TerritoryData-00094.xml"
    fey_forest:
      server:
        - "NpcData_4.xml"
        - "TerritoryData_4.xml"
      client:
        - "NpcData-00002.xml"
        - "TerritoryData-00095.xml"
dungeons:
  bastion_of_lok:
    server:
      - "NpcData_487.xml"
      - "TerritoryData_487.xml"
    client:
      - "NpcData-00255.xml"
      - "TerritoryData-00217.xml"